name: cortex
services:
    bgce_cortex:
        image: nesohq/cortex
        container_name: categories
        build:
            context: .
        ports:
            - "5000:80"
        environment:
            VERSION: 1.0.0
            MODE: debug
            SERVICE_NAME: cortex
            HTTP_PORT: 80
            MIGRATION_SOURCE: migrations
            JWT_SECRET: anything-secret

            # APM Configuration
            APM_SERVICE_NAME:
            APM_SERVER_URL:
            APM_SECRET_TOKEN:
            APM_ENVIRONMENT:

            # RabbitMQ
            RABBITMQ_URL: "amqp://admin:admin@localhost:5672"
            RMQ_RECONNECT_DELAY: 5
            RMQ_RETRY_INTERVAL: 600
            RMQ_QUEUE_PREFIX: cortex-dev

            # Read cortex DB
            READ_CORTEX_DB_HOST: 10.70.33.230
            READ_CORTEX_DB_PORT: 5432
            READ_CORTEX_DB_NAME: bgce
            READ_CORTEX_DB_USER: postgres
            READ_CORTEX_DB_PASSWORD: postgres
            READ_CORTEX_DB_MAX_IDLE_TIME_IN_MINUTES: 60
            READ_CORTEX_DB_MAX_OPEN_CONNS: 25
            READ_CORTEX_DB_MAX_IDLE_CONNS: 25
            READ_CORTEX_DB_ENABLE_SSL_MODE: false

            # Write cortex DB
            WRITE_CORTEX_DB_HOST: 10.70.33.230
            WRITE_CORTEX_DB_PORT: 5432
            WRITE_CORTEX_DB_NAME: bgce
            WRITE_CORTEX_DB_USER: postgres
            WRITE_CORTEX_DB_PASSWORD: postgres
            WRITE_CORTEX_DB_MAX_IDLE_TIME_IN_MINUTES: 60
            WRITE_CORTEX_DB_MAX_OPEN_CONNS: 25
            WRITE_CORTEX_DB_MAX_IDLE_CONNS: 25
            WRITE_CORTEX_DB_ENABLE_SSL_MODE: false
