name: "Cache Go modules and build"

description: "Caches Go build cache and modules"

inputs:
  modulePath:
    description: "Relative path to the go.sum file"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: ♻️ Cache Go modules and build
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.sum', inputs.modulePath)) }}
        restore-keys: |
          ${{ runner.os }}-go-
