name: Go Tests [MATRIX STRATEGY]

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Run Go Tests in ${{ matrix.service }} service
        runs-on: ubuntu-latest

        strategy:
            matrix:
                service: [cortex, skeleton] # Add more services here as needed

        steps:
            - name: ⬇️ Checkout
              uses: actions/checkout@v3

            - name: Cache Go modules and build (reusable)
              uses: ./.github/actions/go-cache
              with:
                  modulePath: ${{ matrix.service }}

            - name: Run Go tests
              run: |
                  cd ${{ matrix.service }}
                  go mod tidy
                  go test ./... -v
